[luar]
url = "https://github.com/gustavo-hms/luar"

[luar.peneira]
url = "https://github.com/gustavo-hms/peneira"

[auto-pairs]
url = "https://github.com/alexherbo2/auto-pairs.kak"
config = """
enable-auto-pairs
"""
