[package]
name = "almoxarife"
version = "0.1.0"
edition = "2021"

[dependencies]
url = "2.2"
yaml-rust = "0.4.5"
anyhow = "1.0"
thiserror = "1.0.31"
colorized = "1.0.0"

[dev-dependencies]
tempfile = "3.3"

[[bin]]
name = "al"
path = "src/main.rs"
