[package]
name = "balaio"
version = "0.1.0"
edition = "2021"

[dependencies]
url = "2.2"
async-std = { version = "1.11.0", features = [ "unstable", "attributes" ] }
yaml-rust = "0.4.5"
anyhow = "1.0"
futures = "0.3"

[dev-dependencies]
tempfile = "3.3"
